name: Docker Build and Push
on:
  push:
    branches:
      - master
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      # 拉去代码
      - name: Checkout code
        uses: actions/checkout@v3
      # 设置jdk还环境
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      # 打包
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      # 登录阿里云
      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_CR_USER }}
          password: ${{ secrets.ALIYUN_CR_PWD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.cn-shanghai.aliyuncs.com/z-zg/github:latest
