steps:
  - uses: actions/checkout@v4
  - name: Set up JDK 21 for x64
    uses: actions/setup-java@v4
    with:
      java-version: '21'
      distribution: 'temurin'
      cache: maven
      name: Package
      path: staging
  - name: Run the Maven verify phase
    run: mvn --batch-mode --update-snapshots verify
  - name: Build with Maven
    run: mvn --batch-mode --update-snapshots verify
  - run: mvn --batch-mode --update-snapshots verify

